### ISSUE TITLE
about sendRawTransaction

### ISSUE THREAD

**Issue by frankkeepgoing** [czbag/zksync#1]
can't 100% ensure this is one issue, but when i change the code from txn_hash = web3.eth.sendRawTransaction(signed_txn) to txn_hash = web3.eth.sendRawTransaction(signed_txn.**rawTransaction**), it's working fine.

**Comment by czbag** [comment]
1) make transaction: 
`transaction = contract.functions.SameFuctionName(params).build_transaction(tx_data)`
2) sign tx: 
`signed_txn = w3.eth.account.sign_transaction(transaction, private_key)`
3) send raw tx:
`txn_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)`

more info: https://web3py.readthedocs.io/en/stable/index.html
